#!/bin/bash
export OPENSHIFT_BACKUP_RESTORE=TRUE

#echo "Deleting tv_listings and tv_channels collection..."
#MONGO_URI="$OPENSHIFT_MONGODB_DB_HOST:$OPENSHIFT_MONGODB_DB_PORT/$OPENSHIFT_MONGODB_DB_NAME"
#echo $MONGO_URI

#mongo $MONGO_URI -u $OPENSHIFT_MONGODB_USER_NAME -p $OPENSHIFT_MONGODB_USER_PASS --eval "db.getCollection('tv_listings').drop(); db.getCollection('tv_channels').drop()"
#echo "Running mongorestore..."
mongorestore --host $OPENSHIFT_MONGODB_DB_HOST --port $OPENSHIFT_MONGODB_DB_PORT --username $OPENSHIFT_MONGODB_USER_NAME --password $OPENSHIFT_MONGODB_USER_PASS --db $OPENSHIFT_MONGODB_DB_NAME --drop --dir $OPENSHIFT_REPO_DIR./tasks/dump
echo "Completed restore!"

export OPENSHIFT_BACKUP_RESTORE=FALSE