#!/bin/sh
export OPENSHIFT_BACKUP_RESTORE=TRUE

echo "Deleting tv_listings and tv_channels collection..."
MONGO_URI = "mongodb://" $OPENSHIFT_MONGODB_USER_NAME ":" $OPENSHIFT_MONGODB_USER_PASS "@" $OPENSHIFT_MONGODB_DB_HOST ":" $OPENSHIFT_MONGODB_DB_PORT
echo $MONGO_URI

mongo $MONGO_URI --eval "db.getCollection('tv_listings').drop(); db.getCollection('tv_channels').drop()"
echo "Running mongorestore..."
mongorestore --host $OPENSHIFT_MONGODB_DB_HOST --port $OPENSHIFT_MONGODB_DB_PORT --username $OPENSHIFT_MONGODB_USER_NAME --password $OPENSHIFT_MONGODB_USER_PASS $OPENSHIFT_PYTHON_DIR/tasks/dump
echo "Completed restore!"

export OPENSHIFT_BACKUP_RESTORE=FALSE
