"""empty message

Revision ID: 17f460375af3
Revises: 24910956c777
Create Date: 2015-07-31 18:51:48.128000

"""

# revision identifiers, used by Alembic.
revision = '17f460375af3'
down_revision = '24910956c777'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('ms_progid', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'channel', sa.Column('channel_id_airtel', sa.String(length=40), nullable=True))
    op.add_column(u'channel', sa.Column('channel_id_cable', sa.String(length=40), nullable=True))
    op.add_column(u'channel', sa.Column('channel_id_tata_sky', sa.String(length=40), nullable=True))
    op.add_column(u'channel', sa.Column('channel_no_airtel', sa.String(length=6), nullable=True))
    op.add_column(u'channel', sa.Column('channel_no_cable', sa.String(length=6), nullable=True))
    op.add_column(u'channel', sa.Column('channel_no_tata_sky', sa.String(length=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'channel', 'channel_no_tata_sky')
    op.drop_column(u'channel', 'channel_no_cable')
    op.drop_column(u'channel', 'channel_no_airtel')
    op.drop_column(u'channel', 'channel_id_tata_sky')
    op.drop_column(u'channel', 'channel_id_cable')
    op.drop_column(u'channel', 'channel_id_airtel')
    op.drop_table('programme')
    ### end Alembic commands ###
