"""empty message

Revision ID: 24910956c777
Revises: None
Create Date: 2015-07-30 20:24:33.645000

"""

# revision identifiers, used by Alembic.
revision = '24910956c777'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    ### end Alembic commands ###
